version: 0.2

phases:
  pre_build:
    commands:
      - echo $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - sed -i.bak "s|REPLACE_WITH_IMAGE_URL|$REPOSITORY_URI|g" container-definitions.json
      - cat container-definitions.json

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      # Register the new ECS task definition using the :latest tag
      - NEW_REVISION=$(aws ecs register-task-definition --family $TASK_FAMILY --container-definitions file://container-definitions.json --query 'taskDefinition.revision' --output text)
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $TASK_FAMILY:$NEW_REVISION
